	package ActionListener;


import javax.swing.*;
import java.awt.*;
import java.awt.event.*;	//	 or  java.awt.event.ActionListener; and java.awt.event.ActionEvent;



// ActionListener = Is an interface in Java Swing used to handle events generated by user actions, such as button clicks




public class ActionListenerPractice {

	public static void main(String[] args) {	
		
		JButton button1 = new JButton("RANDOM");
		backendLogic actionListener = new backendLogic();
			button1.addActionListener(actionListener);
		
		
		
		JPanel myPanel = new JPanel(new FlowLayout());
		myPanel.setBackground(Color.white);
		myPanel.add(button1);
		myPanel.setVisible(true);
		
		
		
		
		JFrame myFrame = new JFrame("ActionListener Application");
		myFrame.setSize(500,500);
		myFrame.setLocationRelativeTo(null);
		myFrame.setLayout(new BorderLayout());
		myFrame.add(myPanel, BorderLayout.CENTER);
		myFrame.setVisible(true);
		
	}
	
	
	
	
		public static class backendLogic implements ActionListener {   // Implement the actionlistener method
			@Override	
			public void actionPerformed(ActionEvent e) {   // Implement the action that will be performed inside the inner method
				JOptionPane.showMessageDialog(null, "Button Clicked");   // The action performed		
			}	
		} // Attach this backendLogic to the component you wanted this to have	
		
		
		
		
}
